services:
  db:
    image: postgres:16.3-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
